name: Clang Format Code

# TODO: Remove main branch at some point
on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: "./code"
        extensions: 'h,cpp'
        clangFormatVersion: 14
        style: file
        inplace: True

    - uses: EndBug/add-and-commit@v4
      with:
        author_name: Clang Robot
        author_email: robot@phlexplexi.co
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}